### ISSUE TITLE
Polling analytics

### ISSUE THREAD

**Issue by smoore4moma** [BarnesFoundation/acme-ticketing-client#2]
Some really great stuff here @cjativa .  I understand that polling analytics is done either through a number of tries or a timer in a loop. Do you happen to have an example of how you are polling for report results?  Thanks.  Steve

**Comment by cjativa** [comment]
Thanks @smoore4moma.

Yes that's right -- for polling we're doing it on an interval throughout our code application code. 

Here's an [example for our test examples](https://github.com/BarnesFoundation/acme-ticketing-client/blob/master/tests/test.ts#L43).

The example could use some improvement, but that's how we'd typically do it
1. Poll every 1 second
2. Check if the report status returns a status of 'Completed' and end the interval when that occurs
3. Exit out of the interval if the report hasn't moved to complete after X amount of times


Something like this might be simpler, I haven't set a timeout though in this example.
```
// Poll until report status is complete
	const pollUntilComplete = () => {
		return new Promise((resolve) => {
			const interval = setInterval(async () => {

                                const status = (await ReportFunctions.pollForReportStatus(id)).status;
                                console.log(`Report status is ${status}.`);

				if (status === 'Completed') {
					console.log('Report execution completed. Ending polling');
					resolve();
                                        clearInterval(interval);
				}

			}, 1000);
		});
	}

```

**Comment by smoore4moma** [comment]
Perfect.  Thanks for the example!  I think I'll add a timeout.  Working on calling the ACME api via a report and then writing to Google Cloud Storage as csv.  That, in theory, will cause a trigger to fire to import it into BigQuery.  All for a new data warehouse that I am working on.

I just posted this on the NetX slack (netxmuseums.slack.com) because I thought it was excellent.  And people are asking me all the time about TMS-NetX syncs. 

https://github.com/BarnesFoundation/dams-sync

PS, The search endpoints do not seem to be working.  I think they realized that you could call data without polling and shut it down.  This was working last week for example.  It doesn't now.

`https://backoffice.acmeticketing.com/v2/api/order/summaries/search?pageSize=0&page=0&sortField=createdOn&sortDirection=desc&startDate=2021-04-28T00%3A00%3A00-0400&endDate=2021-04-28T23%3A59%3A59-0400`
